version: 2.1

executors:
  meetup:
    docker:
      # Main image to be used within this configuration
      - image: circleci/node:12.14.1
        environment: # environment variables for database
          NODE_ENV: test
          TEST_DB_USERNAME: postgres
          TEST_DB_PASSWORD: ''
          TEST_DB_NAME: test
          TEST_DB_HOST: localhost
          CC_TEST_REPORTER_ID: '70bc935693ed7d6de36c68b2007c1afbe5ea81cf28178c4dfded88805a2d9736'

      # Environment variables for database need to match DATABASE_URL
      - image: circleci/postgres:10-alpine-ram
        environment:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''

jobs:
  prepare:
    executor: meetup
    steps:
      - checkout
      - run: sudo npm install
      - save_cache:
          key: disposables-cache-1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

  tests:
    executor: meetup
    steps:
      - checkout
      - run:
          name: Runtest with Code Climate test-reporter
          command: |
            ./cc-test-reporter before-build
            npm test --coverage-clover clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

  report:
    executor: meetup
    steps:
      - checkout
      - run: npm run coveralls

workflows:
  'Run tests':
    jobs:
      - prepare
      - tests:
          requires:
            - prepare
      - report:
          requires:
            - prepare
            - tests
